server:
  port: 8761  #Service Discovery ???? ?? ?? ?? ??

spring:
  application:
    name: discoveryservice

eureka:
  client:
    register-with-eureka: false #?? ?? Eureka??? ??? ???? ??. ?, ?? ?? ?? ??????? Eureka ??? ?? ?? ? ??
    fetch-registry: false #Eureka ???? ?? ??? ?????(?? ????? ??)? ???? ??